spring.application.name=require4testing

# Prevents the container from being restarted every time
spring.docker.compose.lifecycle-management=start_only

# JWT
# In Production we'll use Vault or env variable
jwt.secret=4e635266556a586e2f413f4428472b4b6250655368566d597133743677397a24
jwt.expiration=86400000
jwt.refresh-token.expiration=604800000


# Spring Data JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/requirefortesting
spring.datasource.username=myuser
spring.datasource.password=secret

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
