spring:
  application:
    name: requirefortesting

  datasource:
    name: requirefortesting
    url: "jdbc:postgresql://localhost:5432/requirefortesting"
    password: secret
    username: myuser
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  docker:
    compose:
      lifecycle-management: none