spring.application.name=require4testing
# Prevents the container from being restarted every time
spring.docker.compose.lifecycle-management=start_only
# Spring Data JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/requirefortesting
spring.datasource.username=myuser
spring.datasource.password=secret
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Logging
logging.level.org.springframework.security=TRACE
