spring:
  application:
    name: requirefortesting


  datasource:
    name: requirefortesting
    url: "jdbc:postgresql://localhost:5432/requirefortesting"
    password: secret
    username: myuser
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update